apiVersion: batch/v1
kind: Job
metadata:
  name: db-init-job
  namespace: default
spec:
  backoffLimit: 3                       
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never             
      containers:
      - name: db-init
        image: bitnami/postgresql:15
        env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: PGPASSWORD
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: PGUSER
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: PGHOST
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: pg-credentials
              key: PGPORT
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -e
            echo "ðŸ” Waiting for DNS resolution..."
            for i in {1..50}; do
              if getent hosts "$PGHOST" > /dev/null; then
                echo "DNS resolved for $PGHOST"
                break
              fi
              echo "Waiting for DNS to resolve $PGHOST..."
              sleep 5
            done
            
            echo "Checking if database exists..."
            DB_EXISTS=$(psql "host=$PGHOST port=$PGPORT user=$PGUSER dbname=defaultdb sslmode=require" -tAc "SELECT 1 FROM pg_database WHERE datname='voting'")
            
            if [[ "$DB_EXISTS" != "1" ]]; then
              echo "Creating database 'voting'..."
              psql "host=$PGHOST port=$PGPORT user=$PGUSER dbname=defaultdb sslmode=require" -c "CREATE DATABASE voting;"
            else
              echo "Database 'voting' already exists, skipping."
            fi
            
            echo "Creating table if not exists..."
            psql "host=$PGHOST port=$PGPORT user=$PGUSER dbname=voting sslmode=require" -v ON_ERROR_STOP=1 -c \
            "CREATE TABLE IF NOT EXISTS votes (id SERIAL PRIMARY KEY, vote VARCHAR(255) NOT NULL);"
            
            echo "Database and table are ready."
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
