apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    app: result
spec:
  type: LoadBalancer
  selector:
    app: result
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
