apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres
        command:
          - sh
          - -c
          - |
            until pg_isready -h "$POSTGRES_HOST" -p "$PGPORT" -U "$POSTGRES_USER"; do echo "Waiting for DB..."; sleep 3; done
        envFrom:
          - secretRef:
              name: pg-credentials

      containers:
      - name: result
        image: ghcr.io/sandipgangdhar/voting-app-result:latest
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: pg-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  selector:
    app: result
  ports:
  - port: 80
    targetPort: 80
