apiVersion: batch/v1
kind: Job
metadata:
  name: traffic-generator
spec:
  template:
    spec:
      containers:
      - name: hey
        image: williamyeh/hey
        args: ["-z", "60s", "-c", "5", "http://vote"]
      restartPolicy: Never
  backoffLimit: 4